//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kigg.Infrastructure.HtmlAgilityPack.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LargeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LargeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kigg.Infrastructure.HtmlAgilityPack.Test.LargeStrings", typeof(LargeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;By Line Removal Test&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div id=&quot;content&quot;&gt;
        ///&lt;p&gt;By KodefuGuru, © 2009, All Rights Reserved&lt;/p&gt;
        ///&lt;p&gt;Chinese martial arts, known in Mandarin as wushu and popularly as kungfu, consist of a number of fighting styles that were developed over the centuries. Those fighting styles can be classified [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ByLineHtml {
            get {
                return ResourceManager.GetString("ByLineHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese martial arts, known in Mandarin as wushu and popularly as kungfu, consist of a number of fighting styles that were developed over the centuries. Those fighting styles can be classified according to common themes that are identified as &quot;families&quot;, &quot;sects&quot; or &quot;schools&quot; of martial arts. Example of themes are physical exercises that mimic movements from animals or a history and training method that gather inspiration from various Chinese philosophies, myths and legends. Some styles focus on the the h....
        /// </summary>
        internal static string ByLineText {
            get {
                return ResourceManager.GetString("ByLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;Date Removal Test&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div id=&quot;content&quot;&gt;
        ///&lt;p&gt;Tuesday, September 16, 2008&lt;/p&gt;
        ///&lt;p&gt;Chinese martial arts, known in Mandarin as wushu and popularly as kungfu, consist of a number of fighting styles that were developed over the centuries. Those fighting styles can be classified according to comm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DateLineHtml {
            get {
                return ResourceManager.GetString("DateLineHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese martial arts, known in Mandarin as wushu and popularly as kungfu, consist of a number of fighting styles that were developed over the centuries. Those fighting styles can be classified according to common themes that are identified as &quot;families&quot;, &quot;sects&quot; or &quot;schools&quot; of martial arts. Example of themes are physical exercises that mimic movements from animals or a history and training method that gather inspiration from various Chinese philosophies, myths and legends. Some styles focus on the the h....
        /// </summary>
        internal static string DateLineText {
            get {
                return ResourceManager.GetString("DateLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;H1 Removal Test&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div id=&quot;content&quot;&gt;
        ///&lt;h1&gt;H1 Removal Test&lt;/h1&gt;
        ///&lt;p&gt;Chinese martial arts, known in Mandarin as wushu and popularly as kungfu, consist of a number of fighting styles that were developed over the centuries. Those fighting styles can be classified according to common themes th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string H1Html {
            get {
                return ResourceManager.GetString("H1Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese martial arts, known in Mandarin as wushu and popularly as kungfu, consist of a number of fighting styles that were developed over the centuries. Those fighting styles can be classified according to common themes that are identified as &quot;families&quot;, &quot;sects&quot; or &quot;schools&quot; of martial arts. Example of themes are physical exercises that mimic movements from animals or a history and training method that gather inspiration from various Chinese philosophies, myths and legends. Some styles focus on the the h....
        /// </summary>
        internal static string H1Text {
            get {
                return ResourceManager.GetString("H1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;&lt;meta name=&quot;description&quot; content=&quot;Microsoft portal site for the ASP.NET development community. Download Visual Web Developer, post to the forums, read ASP.net blogs and learn about ASP.net.&quot; /&gt;&lt;meta name=&quot;keywords&quot; content=&quot;ASP.NET, ASP.NET 2.0, Whidbey, .aspx, .ascx, Web, HTML, Developer, Internet, Microsoft, Web Services, Visual Studi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html1 {
            get {
                return ResourceManager.GetString("Html1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional-dtd&quot;&gt; 
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot; lang=&quot;en&quot;&gt;
        ///&lt;head id=&quot;ctl00_ctl00&quot;&gt;&lt;meta name=&quot;description&quot; content=&quot;Kazi Manzur Rashid&amp;#39;s Blog - Sharing Thoughts and Learning on Microsoft .NET Technology&quot; /&gt;
        ///&lt;meta name=&quot;keywords&quot; content=&quot;Kazi Manzur Rashid, Amit, ASP.NET, ASP.NET  AJAX, ASPMVC, AJAX, C#, .NET, SQL, Linq, TDD, DDD, BDD&quot; /&gt;
        ///&lt;meta name=&quot;GENERATOR&quot; content= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html2 {
            get {
                return ResourceManager.GetString("Html2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot;
        ///	&quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; id=&quot;sixapart-standard&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///	&lt;meta name=&quot;generator&quot; content=&quot;http://www.typepad.com/&quot; /&gt;
        ///	
        ///	
        ///	
        ///	&lt;meta name=&quot;description&quot; content=&quot;Yesterday, we published xUnit.net release 1.1.In addition to new features like TeamCity support, there are also several breaking chan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html3 {
            get {
                return ResourceManager.GetString("Html3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en-GB&quot; lang=&quot;en-GB&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;link rel=&quot;shortcut icon&quot; href=&quot;http://lessthandot.com//favicon.ico&quot; type=&quot;image/vnd.microsoft.icon&quot; /&gt;
        ///		&lt;base href=&quot;http://blogs.lessthandot.com/skins/MicroDot/&quot; /&gt;	&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;/plugins/code_highlight_plugin/bbGeSHi.css&quot; /&gt;
        ///&lt;!--[if IE]&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ////* IE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html4 {
            get {
                return ResourceManager.GetString("Html4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///
        ///&lt;title&gt;Then a Miracle Occurs - Public Beta - Blog - Stack Overflow&lt;/title&gt;
        ///
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;http://blog.stackoverflow.com/wp-content/themes/zimpleza/style.css&quot; type=&quot;text/css&quot; media=&quot;screen&quot; /&gt;
        ///&lt;link rel=&quot;alternate&quot; type=&quot;application/rss+xml&quot; ti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html5 {
            get {
                return ResourceManager.GetString("Html5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnglishGermanSpanishFrenchChinese
        ///					Home
        ///					Get Started
        ///					Learn
        ///					Downloads
        ///					AJAX
        ///					Community
        ///					Wiki (Beta)
        ///					ForumsSign InJoinWelcomeWhy ASP.NET?
        ///ASP.NET is a free technology that allows anyone to create a modern web site.
        ///Start with ASP.NETGet ASP.NET - Free
        ///ASP.NET Framework
        ///ASP.NET AJAX
        ///Visual Web DeveloperLearn ASP.NET
        ///Video Tutorials
        ///Starter Kit Web Sites
        ///Books on ASP.NETIn the NewsNew Updates to the ASP.NET Wiki
        ///
        ///
        ///      The Wiki continues to grow with upd....
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;Test : The Title&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div id=&quot;content&quot;&gt;
        ///&lt;p&gt;By KodefuGuru, © 2009, All Rights Reserved&lt;/p&gt;
        ///&lt;p&gt;Chinese martial arts, known in Mandarin as wushu and popularly as kungfu, consist of a number of fighting styles that were developed over the centuries. Those fighting styles can be classified acc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TitleFilterHtml {
            get {
                return ResourceManager.GetString("TitleFilterHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test :.
        /// </summary>
        internal static string TitleFilters {
            get {
                return ResourceManager.GetString("TitleFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//div[@class=&quot;post-body entry-content&quot;]
        ///.//div[@class=&quot;post xfolkentry&quot;]/div[@class=&quot;text&quot;]
        ///.//div[@class=&quot;articleText&quot;]
        ///.//div[@class=&quot;entry-body&quot;]
        ///.//div[@class=&quot;itemBody&quot;]
        ///.//div[@class=&quot;entry&quot;]
        ///.//div[@class=&quot;entrybody&quot;]
        ///.//div[@class=&quot;entryview&quot;]
        ///.//div[@class=&quot;postview&quot;]
        ///.//div[@class=&quot;item-content&quot;]
        ///.//div[@class=&quot;post-entry&quot;]
        ///.//div[@class=&quot;post-content&quot;]
        ///.//div[@class=&quot;post-body&quot;]
        ///.//div[@class=&quot;post-main&quot;]
        ///.//div[@class=&quot;BlogPostContent&quot;]
        ///.//div[@class=&quot;story&quot;]
        ///.//div[@class=&quot;arti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XPaths {
            get {
                return ResourceManager.GetString("XPaths", resourceCulture);
            }
        }
    }
}
