// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Get", Scope = "member", Target = "Kigg.LinqToSql.Repository.IDatabaseFactory.#Get()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "Kigg.LinqToSql.Repository.IDatabase.#GetQueryable`1()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "Kigg.LinqToSql.Repository.IDatabase.#GetEditable`1()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "Kigg.LinqToSql.Repository.IDatabase.#ExecuteQuery`1(System.String,System.Object[])")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Subscribtion", Scope = "member", Target = "Kigg.LinqToSql.Repository.IDatabase.#CommentSubscribtionDataSource")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Spams", Scope = "member", Target = "Kigg.LinqToSql.Repository.Database.#StoryMarkAsSpams")]
[assembly: SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "Kigg.LinqToSql.Repository.Database.#Kigg.LinqToSql.Repository.IDatabase.ExecuteQuery`1(System.String,System.Object[])")]
[assembly: SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "Kigg.LinqToSql.Repository.Database.#GetQueryable`1()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "Kigg.LinqToSql.Repository.Database.#GetEditable`1()")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Subscribtions", Scope = "member", Target = "Kigg.LinqToSql.Repository.Database.#CommentSubscribtions")]
[assembly: SuppressMessage("Microsoft.Design", "CA1063:ImplementIDisposableCorrectly", Scope = "type", Target = "Kigg.LinqToSql.Repository.Database")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.UserTag.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.UserTag.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.UserScore.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.UserScore.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.User.#UserTags")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.User.#UserScores")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.User.#StoryVotes")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Spams", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.User.#StoryMarkAsSpams")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.User.#StoryMarkAsSpams")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.User.#StoryComments")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.User.#Stories")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.User.#OnSerializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.User.#OnSerializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.User.#OnSerialized(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.User.#OnSerialized(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.User.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.User.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Subscribtions", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.User.#CommentSubscribtions")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.User.#CommentSubscribtions")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.User.#ChangeEmail(System.String)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Tag.#UserTags")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Tag.#StoryTags")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Tag.#OnSerializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Tag.#OnSerializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Tag.#OnSerialized(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Tag.#OnSerialized(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Tag.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Tag.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.StoryVote.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.StoryVote.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.StoryView.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.StoryView.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.StoryTag.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.StoryTag.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.StoryMarkAsSpam.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.StoryMarkAsSpam.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.StoryComment.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.StoryComment.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Story.#UrlHash")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Story.#StoryVotes")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Story.#StoryViews")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Story.#StoryTags")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Spams", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Story.#StoryMarkAsSpams")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Story.#StoryMarkAsSpams")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Story.#StoryComments")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Story.#OnSerializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Story.#OnSerializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Story.#OnSerialized(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Story.#OnSerialized(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Story.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Story.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Subscribtions", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Story.#CommentSubscribtions")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Story.#CommentSubscribtions")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.KnownSource.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.KnownSource.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.KnownSource.#Initialize()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.DomainObjectFactory.#CreateUser(System.String,System.String,System.String)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.DomainObjectFactory.#CreateKnownSource(System.String)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.CommentSubscribtion.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.CommentSubscribtion.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Subscribtion", Scope = "type", Target = "Kigg.LinqToSql.DomainObjects.CommentSubscribtion")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Category.#Stories")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Category.#OnSerializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Category.#OnSerializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Category.#OnSerialized(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Category.#OnSerialized(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "context", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Category.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2238:ImplementSerializationMethodsCorrectly", Scope = "member", Target = "Kigg.LinqToSql.DomainObjects.Category.#OnDeserializing(System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Kigg")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Kigg", Scope = "namespace", Target = "Kigg.LinqToSql.Repository")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Kigg", Scope = "namespace", Target = "Kigg.LinqToSql.DomainObjects")]
[assembly: SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "Kigg.LinqToSql.Repository.BaseRepository`2.#BuildPagedResult`1(System.Collections.IEnumerable,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Subscribtion", Scope = "type", Target = "Kigg.LinqToSql.Repository.CommentSubscribtionRepository")]