<?xml version="1.0" encoding="utf-8"?>
<Database Name="Kigg" Class="ManiakDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLExpress;Initial Catalog=Kigg;Integrated Security=True" SettingsObjectName="PowerPivotDotnetomaniak.Properties.Settings" SettingsPropertyName="KiggConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Story" Member="Stories">
    <Type Name="Story">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UniqueName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="HtmlDescription" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TextDescription" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(2048) NOT NULL" CanBeNull="false" />
      <Column Name="UrlHash" Type="System.String" DbType="NChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IPAddress" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SpammedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PublishedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Rank" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastProcessedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ApprovedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Story_StoryTag" Member="StoryTags" ThisKey="Id" OtherKey="StoryId" Type="StoryTag" />
      <Association Name="Story_StoryComment" Member="StoryComments" ThisKey="Id" OtherKey="StoryId" Type="StoryComment" />
      <Association Name="Story_StoryView" Member="StoryViews" ThisKey="Id" OtherKey="StoryId" Type="StoryView" />
      <Association Name="Story_StoryVote" Member="StoryVotes" ThisKey="Id" OtherKey="StoryId" Type="StoryVote" />
      <Association Name="Category_Story" Member="Category" ThisKey="CategoryId" OtherKey="Id" Type="Category" IsForeignKey="true" />
      <Association Name="User_Story" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tag" Member="Tags">
    <Type Name="Tag">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UniqueName" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Tag_StoryTag" Member="StoryTags" ThisKey="Id" OtherKey="TagId" Type="StoryTag" />
      <Association Name="Tag_UserTag" Member="UserTags" ThisKey="Id" OtherKey="TagId" Type="UserTag" />
    </Type>
  </Table>
  <Table Name="dbo.StoryTag" Member="StoryTags">
    <Type Name="StoryTag">
      <Column Name="StoryId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TagId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Story_StoryTag" Member="Story" ThisKey="StoryId" OtherKey="Id" Type="Story" IsForeignKey="true" />
      <Association Name="Tag_StoryTag" Member="Tag" ThisKey="TagId" OtherKey="Id" Type="Tag" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UniqueName" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Category_Story" Member="Stories" ThisKey="Id" OtherKey="CategoryId" Type="Story" />
    </Type>
  </Table>
  <Table Name="dbo.StoryComment" Member="StoryComments">
    <Type Name="StoryComment">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HtmlBody" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TextBody" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StoryId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IPAddress" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="IsOffended" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Story_StoryComment" Member="Story" ThisKey="StoryId" OtherKey="Id" Type="Story" IsForeignKey="true" />
      <Association Name="User_StoryComment" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_Story" Member="Stories" ThisKey="Id" OtherKey="UserId" Type="Story" />
      <Association Name="User_StoryComment" Member="StoryComments" ThisKey="Id" OtherKey="UserId" Type="StoryComment" />
      <Association Name="User_UserScore" Member="UserScores" ThisKey="Id" OtherKey="UserId" Type="UserScore" />
      <Association Name="User_UserTag" Member="UserTags" ThisKey="Id" OtherKey="UserId" Type="UserTag" />
      <Association Name="User_StoryVote" Member="StoryVotes" ThisKey="Id" OtherKey="UserId" Type="StoryVote" />
    </Type>
  </Table>
  <Table Name="dbo.UserScore" Member="UserScores">
    <Type Name="UserScore">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ActionType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Score" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Association Name="User_UserScore" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserTag" Member="UserTags">
    <Type Name="UserTag">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TagId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Tag_UserTag" Member="Tag" ThisKey="TagId" OtherKey="Id" Type="Tag" IsForeignKey="true" />
      <Association Name="User_UserTag" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StoryView" Member="StoryViews">
    <Type Name="StoryView">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StoryId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IPAddress" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="Story_StoryView" Member="Story" ThisKey="StoryId" OtherKey="Id" Type="Story" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StoryVote" Member="StoryVotes">
    <Type Name="StoryVote">
      <Column Name="StoryId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IPAddress" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Story_StoryVote" Member="Story" ThisKey="StoryId" OtherKey="Id" Type="Story" IsForeignKey="true" />
      <Association Name="User_StoryVote" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>