//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kigg.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kigg.Web.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dziesięciotysięcznik.
        /// </summary>
        internal static string _10kPointsBadge {
            get {
                return ResourceManager.GetString("_10kPointsBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tysięcznik.
        /// </summary>
        internal static string _1kPointsBadge {
            get {
                return ResourceManager.GetString("_1kPointsBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentator.
        /// </summary>
        internal static string CommenterBadge {
            get {
                return ResourceManager.GetString("CommenterBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dotnetomaniak.
        /// </summary>
        internal static string DotnetomaniakBadge {
            get {
                return ResourceManager.GetString("DotnetomaniakBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSP&apos;16.
        /// </summary>
        internal static string DSP16FinalistBadge {
            get {
                return ResourceManager.GetString("DSP16FinalistBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSP&apos;17.
        /// </summary>
        internal static string DSP17FinalistBadge {
            get {
                return ResourceManager.GetString("DSP17FinalistBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poranny ptaszek.
        /// </summary>
        internal static string EarlyBirdBadge {
            get {
                return ResourceManager.GetString("EarlyBirdBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string FacebookBadge {
            get {
                return ResourceManager.GetString("FacebookBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Światowiec.
        /// </summary>
        internal static string GlobetrotterBadge {
            get {
                return ResourceManager.GetString("GlobetrotterBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobry artykuł.
        /// </summary>
        internal static string GoodStoryBadge {
            get {
                return ResourceManager.GetString("GoodStoryBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imponujący artykuł.
        /// </summary>
        internal static string GreatStoryBadge {
            get {
                return ResourceManager.GetString("GreatStoryBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomocnik.
        /// </summary>
        internal static string HelperBadge {
            get {
                return ResourceManager.GetString("HelperBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konami Code.
        /// </summary>
        internal static string KonamiCode {
            get {
                return ResourceManager.GetString("KonamiCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über-promotor.
        /// </summary>
        internal static string MultiAdderBadge {
            get {
                return ResourceManager.GetString("MultiAdderBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nocny marek.
        /// </summary>
        internal static string NightOwlBadge {
            get {
                return ResourceManager.GetString("NightOwlBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plakietka.
        /// </summary>
        internal static string PlaqueBadge {
            get {
                return ResourceManager.GetString("PlaqueBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularny artykuł.
        /// </summary>
        internal static string PopularStoryBadge {
            get {
                return ResourceManager.GetString("PopularStoryBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotor.
        /// </summary>
        internal static string StoryAdderBadge {
            get {
                return ResourceManager.GetString("StoryAdderBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podbijacz.
        /// </summary>
        internal static string UpVoteBadge {
            get {
                return ResourceManager.GetString("UpVoteBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niezdecydowany.
        /// </summary>
        internal static string UpVoteDownVote {
            get {
                return ResourceManager.GetString("UpVoteDownVote", resourceCulture);
            }
        }
    }
}
